server:
  port: 8888
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
    mode: HTML5
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      exclude: static/**,public/**

